### PR TITLE
OBS-7 - Add the necessary pipeline template files

### PR DESCRIPTION
**Pull request by Rubber-Duck-999**
I need to get the pipeline setup, there is an awful high amount of work to do for it so I have started with the template files

### CODE REVIEW

**Review by InterpretThisCompileThat — COMMENTED** [review]
I can pull and test these if you'd like, but looks good to me. We can merge and I'll pull and start from here.

**Comment by Rubber-Duck-999** [comment]
Great if you can approve. We are not ready for first release anyway

**Review by InterpretThisCompileThat — APPROVED** [review]

**Review by InterpretThisCompileThat — APPROVED** [review]

**Review by InterpretThisCompileThat — APPROVED** [review]
Looks good to me.

**Comment by Rubber-Duck-999** [comment]
Sorry can you approve again. Its blocked I believe

**Review by InterpretThisCompileThat — APPROVED** [review]

**Review by InterpretThisCompileThat — APPROVED** [review]

**Pull request merged**
